### ISSUE TITLE
Clone render_default hash during inheritance?

### ISSUE THREAD

**Issue by CrowdHailer** [Wardrop/Scorched#33] opened 2015-02-04 08:41 UTC
So I have just wandered into a bug that was caused by the ability for sub controllers to modify the contents of the render_defaults hash. This is a surmised config.ru

```rb
APP_ROOT = File.expand_path('../', __FILE__) unless defined?(APP_ROOT)

require 'scorched'

class App < Scorched::Controller
  render_defaults[:dir] = File.expand_path('app/views', APP_ROOT)
end

class OtherController < App
  render_defaults[:dir] << '/other'
end

class HomeController < App
  render_defaults[:dir] << '/home'
  get '/' do
    render :index
  end
end

App.controller '/', HomeController

run App

```

This will throw the following error, where both other and home have been added to the render path.

> Errno::ENOENT at /
> No such file or directory @ rb_sysopen - /My/Path/app/views/other/home/index.erb

I am happy to be told that the shovel operation with strings there is just bad practise. Thoughts?
But as a suggestion I would deep copy this and the config to children controllers

**Comment by Wardrop** [comment] 2015-02-04 22:43
That would be caused by the shovel operation. Basically, the "child" options hash merges the parent into itself, hence there's no actual string dup'ing. The only way to support the shovel operator (among other mutable operators) is to change Scorched::Options to be copy-on-access. 

There's a caveat to this though. Changing Scorched::Options like this would mean any changes to the a value in the parent hash will be invisible to anyone using the child hash IF that same value has been previously accessed. It creates an ugly situation where in some situations changes to the parent will filter down, but in other instances they won't.

I think it's better left the way it is. One just has to be aware that a simple access such as `render_defaults[:dir]` may return an object (e.g. a string) that is referenced by the parent hash. Basically, use immutable operations in such instances. In your example, replace `<<` with `+=` which will invoke the `[]=` method on the hash. To get a better idea of how this works, check: https://github.com/Wardrop/Scorched/blob/master/lib/scorched/options.rb.

**Comment by CrowdHailer** [comment] 2015-02-06 17:09
I will experiment more with this. Although I think I agree broadly with all your points. and indeed it does seam bad practise to mutate when a just as concise alternative is available. I'm not sure if I like the fact that subsequent changes to the parent filter down. but that’s mostly because I would want to keep my configuration static after set-up

**Comment by Wardrop** [comment] 2015-02-07 23:52
You wouldn't normally make subsequent changes, but as a framework, Scorched shouldn't make any assumptions about how it may be used. More to the point though, when would you lock in those inherited changes into the parent? It needs to always inherit, unless overwritten by the child, for the sake of a consistent system.

**Closed by Wardrop** 2015-02-07 23:52 UTC
